# Generated by Django 5.2.10 on 2026-01-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, help_text='e.g. Metal, Polymer', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='muzzle_velocity_fps',
            field=models.IntegerField(default=0, help_text='Muzzle velocity in FPS'),
        ),
        migrations.AddField(
            model_name='product',
            name='power_supply',
            field=models.CharField(blank=True, help_text='e.g. Gas, AEG, Spring', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_g',
            field=models.IntegerField(default=0, help_text='Weight in grams'),
        ),
    ]
