# Generated by Django 5.2.10 on 2026-01-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_description_en_category_description_pl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color_pl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material_en',
            field=models.CharField(blank=True, help_text='e.g. Metal, Polymer', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material_pl',
            field=models.CharField(blank=True, help_text='e.g. Metal, Polymer', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material_ru',
            field=models.CharField(blank=True, help_text='e.g. Metal, Polymer', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='power_supply_en',
            field=models.CharField(blank=True, help_text='e.g. Gas, AEG, Spring', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='power_supply_pl',
            field=models.CharField(blank=True, help_text='e.g. Gas, AEG, Spring', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='power_supply_ru',
            field=models.CharField(blank=True, help_text='e.g. Gas, AEG, Spring', max_length=100, null=True),
        ),
    ]
